---
vector_version: "0.41.1"
vector_deb_url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
vector_rpm_url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
vector_config_path: "/etc/vector/vector.yaml"
